-- Creating the tables
CREATE TABLE regions (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE states (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    REGION_ID INT,
    FOREIGN KEY (REGION_ID) REFERENCES regions(ID)
);

CREATE TABLE employees (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    STATE_ID INT,
    FOREIGN KEY (STATE_ID) REFERENCES states(ID)
);

CREATE TABLE sales (
    ID INT PRIMARY KEY,
    AMOUNT INT NOT NULL,
    EMPLOYEE_ID INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES employees(ID)
);