INSERT INTO regions(ID, NAME) VALUES(1, 'Noreste');
INSERT INTO regions(ID, NAME) VALUES(2, 'Suroeste');
INSERT INTO regions(ID, NAME) VALUES(3, 'Sureste');
INSERT INTO regions(ID, NAME) VALUES(4, 'Noroeste');

INSERT INTO states(ID, NAME, REGION_ID) VALUES(1, 'Spain', 1);
INSERT INTO states(ID, NAME, REGION_ID) VALUES(2, 'Germany', 2);
INSERT INTO states(ID, NAME, REGION_ID) VALUES(3, 'France', 3);
INSERT INTO states(ID, NAME, REGION_ID) VALUES(4, 'Italy', 4);

INSERT INTO employees(ID, NAME, STATE_ID) VALUES(1, 'Javier', 1);
INSERT INTO employees(ID, NAME, STATE_ID) VALUES(2, 'Ana', 1);
INSERT INTO employees(ID, NAME, STATE_ID) VALUES(3, 'María', 2);
INSERT INTO employees(ID, NAME, STATE_ID) VALUES(4, 'Roberto', 3);
INSERT INTO employees(ID, NAME, STATE_ID) VALUES(5, 'Tomás', 4);

INSERT INTO sales(ID, AMOUNT, EMPLOYEE_ID) VALUES(1, 2000, 1);
INSERT INTO sales(ID, AMOUNT, EMPLOYEE_ID) VALUES(2, 3000, 2);
INSERT INTO sales(ID, AMOUNT, EMPLOYEE_ID) VALUES(3, 4000, 3);
INSERT INTO sales(ID, AMOUNT, EMPLOYEE_ID) VALUES(4, 1200, 4);
INSERT INTO sales(ID, AMOUNT, EMPLOYEE_ID) VALUES(5, 2400, 5);