INSERT INTO REGIONS(NAME) VALUES( 'Espanya');
INSERT INTO REGIONS(NAME) VALUES('Alemanya');
INSERT INTO REGIONS(NAME) VALUES('França');
INSERT INTO REGIONS(NAME) VALUES('Itàlia');

INSERT INTO STATES(NAME, REGION_ID) VALUES('Catalunya', 1L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Andalusia', 1L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Extremadura', 1L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Galicia', 1L);

INSERT INTO STATES(NAME, REGION_ID) VALUES('Bavaria', 2L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Baden-Württemberg', 2L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('North Rhine-Westphalia', 2L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Hesse', 2L);

INSERT INTO STATES(NAME, REGION_ID) VALUES('Île-de-France', 3L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Provence-Alpes-Côte', 3L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Occitanie', 3L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Auvergne-Rhône-Alpes', 3L);

INSERT INTO STATES(NAME, REGION_ID) VALUES('Lazio', 4L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Tuscany', 4L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Lombardy', 4L);
INSERT INTO STATES(NAME, REGION_ID) VALUES('Campania', 4L);

INSERT INTO EMPLOYEES(NAME, STATE_ID) VALUES('Xavier', 1L);
INSERT INTO EMPLOYEES(NAME, STATE_ID) VALUES('Anna', 2L);
INSERT INTO EMPLOYEES(NAME, STATE_ID) VALUES('María', 3L);
INSERT INTO EMPLOYEES(NAME, STATE_ID) VALUES('Robert', 4L);
INSERT INTO EMPLOYEES(NAME, STATE_ID) VALUES('Tomàs', 5L);

INSERT INTO SALES(AMOUNT, EMPLOYEE_ID) VALUES(2000, 1L);
INSERT INTO SALES(AMOUNT, EMPLOYEE_ID) VALUES(3000, 2L);
INSERT INTO SALES(AMOUNT, EMPLOYEE_ID) VALUES(4000, 3L);
INSERT INTO SALES(AMOUNT, EMPLOYEE_ID) VALUES(1200, 4L);
INSERT INTO SALES(AMOUNT, EMPLOYEE_ID) VALUES(2400, 5L);